### ISSUE TITLE
Cmake version

### ISSUE THREAD

**Issue by roboticanyair** [zt-luo/QuickWidgetPlayer#1]
Hi. I'm trying to port your project to cmake, with no luck so far.
is there any chance you already have cmakelists.txt file for this project?

thanks!

**Comment by zt-luo** [comment]
> Hi. I'm trying to port your project to cmake, with no luck so far.
> is there any chance you already have cmakelists.txt file for this project?
> 
> thanks!

check the new commit

**Comment by roboticanyair** [comment]
Works!
thanks a lot man!
